### PR TITLE
* added a waffle for pagination_url

### PR DESCRIPTION
**Pull request by xroot88**
JIRA:NCP-1831

### CODE REVIEW

**Comment by xroot88** [comment]
** DO NOT MERGE **

**Comment by stajkowski** [comment]
How would we get the environment name into the url?

**Comment by roaet** [comment]
@stajkowski that's what we want you to tell us :heart:

**Comment by roaet** [comment]
Can this be merged?

**Comment by xroot88** [comment]
this can be merged

**Pull request merged**
