### PR TITLE
Dropping py26 from travis

### PR DESCRIPTION
**Pull request by roaet**

### CODE REVIEW

**Comment by brandonlogan** [comment]
Anyway to do a recheck on this? I think getting this in would allow my PR to pass the tests.

**Comment by roaet** [comment]
git commit--amend
Force push

You may need to rebase

**Comment by brandonlogan** [comment]
I don't have perms on this repo to push to the branch.  I could do a PR from my fork but that'd just be duplicating this PR.

**Comment by roaet** [comment]
@brandonlogan workin it

**Pull request merged**
